---
- name: Disable Azure Arc Extension
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - arc_hosts is defined
          - region is defined
          - extension
        fail_msg: "Required variables not set"

    - name: Disable Key Vault on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.azure_key_vault.name }}"
        arc_type: "{{ extensions.azure_key_vault.type }}"
        arc_publisher: "{{ extensions.azure_key_vault.publisher }}"
      when: extension == "azure_key_vault"

    - name: Disable Hybrid Worker on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.azure_hybrid_runbook.name }}"
        arc_type: "{{ extensions.azure_hybrid_runbook.type }}"
        arc_publisher: "{{ extensions.azure_hybrid_runbook.publisher }}"
      when: extension == "azure_hybrid_runbook"

    - name: Disable Azure Monitor on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.azure_monitor_agent.name }}"
        arc_type: "{{ extensions.azure_monitor_agent.type }}"
        arc_publisher: "{{ extensions.azure_monitor_agent.publisher }}"
      when: extension == "azure_monitor_agent"

    - name: Disable Azure Monitor for VMs Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.azure_monitor_for_vms.name }}"
        arc_type: "{{ extensions.azure_monitor_for_vms.type }}"
        arc_publisher: "{{ extensions.azure_monitor_for_vms.publisher }}"
      when: extension == "azure_monitor_for_vms"

    - name: Disable AD SSH Login on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.ad_ssh_login.name }}"
        arc_type: "{{ extensions.ad_ssh_login.type }}"
        arc_publisher: "{{ extensions.ad_ssh_login.publisher }}"
      when: extension == "ad_ssh_login"

    - name: Disable Custom Scripts on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.custom_script.name }}"
        arc_type: "{{ extensions.custom_script.type }}"
        arc_publisher: "{{ extensions.custom_script.publisher }}"
      when: extension == "custom_script"

    - name: Disable Azure Log Analytics on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.log_analytics_agent.name }}"
        arc_type: "{{ extensions.log_analytics_agent.type }}"
        arc_publisher: "{{ extensions.log_analytics_agent.publisher }}"
      when: extension == "log_analytics_agent"

    - name: Disable Microsoft Defender on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: disable_arc_extension
      vars:
        arc_name: "{{ extensions.microsoft_defender.name }}"
        arc_type: "{{ extensions.microsoft_defender.type }}"
        arc_publisher: "{{ extensions.microsoft_defender.publisher }}"
      when: extension == "microsoft_defender"
