---
hub_vnet_name: hub-vnet
hub_vnet_cidr: "10.0.200.0/23"
hub_subnet_name: hub-subnet
hub_subnet_cidr: "10.0.200.0/24"
route_table_name: "hub-and-spoke-route-table"
spoke1_vnet_name: spoke-1-vnet
spoke1_vnet_cidr: "10.0.202.0/24"
spoke1_subnet_name: spoke-1-subnet
spoke1_subnet_cidr: "10.0.202.0/24"
spoke2_vnet_name: spoke-2-vnet
spoke2_vnet_cidr: "10.0.203.0/24"
spoke2_subnet_name: spoke-2-subnet
spoke2_subnet_cidr: "10.0.203.0/24"
ssh_security_group_name: ssh-security-group
virtual_gw_name: hub-gateway
virtual_gw_sku: Basic
virtual_gw_subnet_cidr: "10.0.201.0/26"
virtual_gw_vpn_type: route_based
vm_disk_type: Standard_LRS
vm_max_price: -1
vm_priority: Spot
vm_sku: "9_2"
vm_size: Standard_A1_v2
vm_username: azureuser
